In [2]:
# Task 1 – Dataset Cleaning
# • Load the Titanic dataset (train.csv).
# • Display the first 10 rows.
# • Check for missing values in each column.
# • Fill missing values in the "Age" column with the mean age.
# • Drop rows where the "Embarked" column is missing.

In [5]:
# Load the Titanic dataset (train.csv)
import seaborn as sns
import pandas as pd
import numpy as np

In [6]:
data=sns.load_dataset('titanic')

In [8]:
# Display the first 10 rows.
data.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [9]:
# • Check for missing values in each column.
data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [20]:
# • Fill missing values in the "Age" column with the mean age.
data['age']=data['age'].fillna(data['age'].mean())

In [36]:
# • Drop rows where the "Embarked" column is missing.
data=data.dropna(subset='embarked')

In [38]:
# Task 2 – Encoding Categorical Data
# • Convert the "Sex" column into numeric (0 = Male, 1 = Female).
# • Apply One-Hot Encoding on the "Embarked" column

In [47]:
# • Convert the "Sex" column into numeric (0 = Male, 1 = Female).
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['sex']=le.fit_transform(data['sex'])
data[['sex']]

C:\Users\Saad Baseer\AppData\Local\Temp\ipykernel_8368\4213650321.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sex']=le.fit_transform(data['sex'])

     sex
0      1
1      0
2      0
3      0
4      1
..   ...
886    1
887    0
888    0
889    1
890    1

[889 rows x 1 columns]

In [51]:
# • Apply One-Hot Encoding on the "Embarked" column
from sklearn.preprocessing import OneHotEncoding

ImportError: cannot import name 'OneHotEncoding' from 'sklearn.preprocessing' (C:\Users\Saad Baseer\anaconda3\Lib\site-packages\sklearn\preprocessing\__init__.py)